import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ChildrenProps} from "@/types/common";
// import SelectedLayoutSegmentComponent from "@/app/selectedLayoutSegment";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  metadataBase: new URL('https://acme.com'),
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
      'de-DE': '/de-DE',
    },
  },
  openGraph: {
    images: '/og-image.png',
  },
}

export default function RootLayout({
  children,
}: ChildrenProps) {
  return (
    <html lang="en">
      <body className={'rootLayout'}>
      {/*<SelectedLayoutSegmentComponent/>*/}

      <p className={'text-green-700'}>레이아웃의 영역으로 다수의 페이지 간에 공유될 UI이다. (상위 레이아웃)</p>
        {children}
      </body>
    </html>
  )
}
